无级倍速 `增加记忆功能` `修复自动切换视频失效问题`
0xlau/biliplus pull request #98
Opened 2024-06-21 06:53 UTC by gantoho

无级倍速 `增加记忆功能` `修复自动切换视频失效问题`

2024-06-21 06:53 UTC, gantoho commented
fixed #45
fixed #89

2024-06-21 16:51 UTC, 0xlau requested changes

2024-06-22 15:03 UTC, gantoho commented
@0xlau 可以讨论一下吗，我确实没有找到需要在什么时机下来断开观察
这和在某个DOM下创建新的内容有所不同，因为创建新的内容只需要一次，紧接着就可以断开观察
但观察video的属性变化，只要是在播放视频界面可能需要持续的进行观察
这是我的理解，但不确定是否正确

2024-06-25 00:00 UTC, closed without merging

2024-11-02 03:48 UTC, ZhangHaHei commented
> 无级倍速 `增加记忆功能` `修复自动切换视频失效问题`

请问最新的仓库里有这个功能吗？我clone main 仓库make之后还是没有记忆功能

2024-11-02 04:13 UTC, ZhangHaHei commented
> > 无级倍速 `增加记忆功能` `修复自动切换视频失效问题`
> 
> 请问最新的仓库里有这个功能吗？我clone main 仓库make之后还是没有记忆功能

已经按照您的提交替换了js，成功，感谢！